definitions:
  models.ApiResponse-models_WorkTeam:
    properties:
      data:
        allOf:
        - $ref: '#/definitions/models.WorkTeam'
        description: Response data
      message:
        description: Descriptive message
        example: Successful operation
        type: string
      status:
        description: Response status
        example: success
        type: string
    type: object
  models.WorkTeam:
    description: Structure representing a work team
    properties:
      created_at:
        example: "2023-01-01T00:00:00Z"
        type: string
      description:
        example: Team responsible for software development
        type: string
      members:
        example:
        - '["user1"'
        - ' "user2"]'
        items:
          type: string
        type: array
      status:
        example: true
        type: boolean
      team_code:
        example: TEAM-001
        type: string
      team_name:
        example: Development Team
        type: string
      updated_at:
        example: "2023-01-01T00:00:00Z"
        type: string
      work_team_id:
        example: 1
        type: integer
    type: object
host: localhost:8181
info:
  contact: {}
  description: API for managing work teams.
  title: Work Team Add API
  version: "1.0"
paths:
  /work-team/add:
    post:
      consumes:
      - application/json
      description: Create a new work team
      parameters:
      - description: Work team data
        in: body
        name: workTeam
        required: true
        schema:
          $ref: '#/definitions/models.WorkTeam'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.ApiResponse-models_WorkTeam'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/models.ApiResponse-models_WorkTeam'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/models.ApiResponse-models_WorkTeam'
      summary: Create a work team
      tags:
      - work-team
schemes:
- http
- https
swagger: "2.0"
