name: CI/CD to EC2

on:
  push:
    branches: [ "QA" ]

jobs:
  build-and-push-images:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build and Push Add Work Team Service Image
        run: |
          docker build -t anggeloo/services-work-team-add:latest ./services-work-team-add
          docker push anggeloo/services-work-team-add:latest

      - name: Build and Push Search Work Team Service Image
        run: |
          docker build -t anggeloo/services-work-team-search:latest ./services-work-team-search
          docker push anggeloo/services-work-team-search:latest

      - name: Build and Push Update Work Team Service Image
        run: |
          docker build -t anggeloo/services-work-team-update:latest ./services-work-team-update
          docker push anggeloo/services-work-team-update:latest

      - name: Build and Push Delete Work Team Service Image
        run: |
          docker build -t anggeloo/services-work-team-delete:latest ./services-work-team-delete
          docker push anggeloo/services-work-team-delete:latest

  deploy-to-ec2:
    needs: build-and-push-images
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to EC2
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          script: |
            # 1) Ir al directorio donde está docker-compose.yml
            cd /home/ubuntu/

            # 2) Descargar las imágenes más recientes de Docker Hub
            docker pull anggeloo/services-work-team-add:latest
            docker pull anggeloo/services-work-team-search:latest
            docker pull anggeloo/services-work-team-update:latest
            docker pull anggeloo/services-work-team-delete:latest

            # 3) Detener y eliminar los contenedores anteriores
            docker-compose down

            # 4) Levantar los nuevos contenedores
            docker-compose up -d --remove-orphans
