name: CI/CD to EC2

on:
  push:
    branches:
      - QA
  pull_request:
    branches:
      - QA

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/work-team-add:latest .
          docker tag ${{ secrets.DOCKER_USERNAME }}/work-team-add:latest ${{ secrets.DOCKER_USERNAME }}/work-team-add:${{ github.sha }}

      - name: Push Docker image
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/work-team-add:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/work-team-add:${{ github.sha }}

  deploy-to-ec2:
    needs: build-and-push-image
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to EC2
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          script: |
            # 1) Navigate to the directory where docker-compose.yml is located
            cd /home/ubuntu/
            
            # 2) Pull the latest image from Docker Hub
            docker pull ${{ secrets.DOCKER_USERNAME }}/work-team-add:latest
            
            # 3) Stop and remove previous containers
            docker-compose down
            
            # 4) Start new containers with the updated image
            docker-compose up -d --remove-orphans