name: CI/CD to EC2 - Work Team Microservices

on:
  push:
    branches: [ "QA" ]

jobs:
  build-and-push-images:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker Image
        run: docker build -t anggeloo/services-work-team-add:latest .

      - name: Push Docker Image
        run: docker push anggeloo/services-work-team-add:latest

  deploy-to-ec2:
    needs: build-and-push-images
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to EC2
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          script: |
            # 1) Change to the directory where docker-compose.yml is located
            cd /home/ubuntu/

            # 2) Download the latest images from Docker Hub
            docker pull anggeloo/services-work-team-add:latest
            docker pull anggeloo/services-work-team-search:latest
            docker pull anggeloo/services-work-team-update:latest
            docker pull anggeloo/services-work-team-delete:latest

            # 3) Stop and remove previous containers
            docker-compose down

            # 4) Push new containers with updated images
            docker-compose up -d --remove-orphans
