name: CI/CD to EC2

on:
  push:
    branches:
      - QA

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/work-team-add:latest .
          docker tag ${{ secrets.DOCKER_USERNAME }}/work-team-add:latest ${{ secrets.DOCKER_USERNAME }}/work-team-add:${{ github.sha }}

      - name: Push Docker image
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/work-team-add:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/work-team-add:${{ github.sha }}

  deploy-to-ec2:
    needs: build-and-push-image
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to EC2
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          script: |
            echo "Starting deployment on EC2..."
            
            # 1) Navegar a la carpeta donde están los archivos de despliegue
            cd /home/ubuntu/

            # 2) Descargar la última imagen del Docker Hub
            docker pull ${{ secrets.DOCKER_USERNAME }}/work-team-add:latest

            # 3) Detener y eliminar contenedores anteriores
            docker-compose down || true

            # 4) Crear o actualizar el archivo .env con las credenciales
            echo "DB_HOST=${{ secrets.DB_HOST }}" > .env
            echo "DB_PORT=${{ secrets.DB_PORT }}" >> .env
            echo "DB_USER=${{ secrets.DB_USER }}" >> .env
            echo "DB_PASSWORD=${{ secrets.DB_PASSWORD }}" >> .env
            echo "DB_NAME=${{ secrets.DB_NAME }}" >> .env
            echo "PORT=${{ secrets.PORT }}" >> .env

            # 5) Verificar que el archivo .env fue creado correctamente
            cat .env

            # 6) Reiniciar y levantar los contenedores
            docker-compose up -d --remove-orphans

            echo "Deployment successfully completed."
